from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import (
	Index_Page,
	Index_User,
	AddCart,
	AddCartEmpty,
	BaseViewCart,
	AddProduct,
	MinusProduct,
	DeleteCart,
	Buy,
	login,
	logout_user,
	confirm,
	ViewSPUserBuy,
	ViewConfirmQL,
	register_user,
	# save_user,
	Present_Page,
	Link,
	Paper,
	ViewDeatail,
)
urlpatterns = [
	url('^$', Index_Page.as_view(), name='page_Index_Page'),	
	url(r'^login_user/$', login, name='page_login'),
	url(r'^register_user/$', register_user, name='register_user'),
	# url(r'^save_user/$', save_user, name='save_user'),
	url(r'^logout_user/$', logout_user, name='page_logout_user'),
	url(r'^present/$', Present_Page, name='page_present_page'),
	url(r'^link/$', Link, name='page_link_page'),
	url(r'^paper/$', Paper, name='page_paper_page'),
	url(r'^index/$', Index_User.as_view(), name='page_Index_User'),
	url(r'^view_deatail/(?P<id_to>\w+)/$', ViewDeatail.as_view(), name='page_ViewDeatail'),
	url(r'^index/is_confirm/$', ViewConfirmQL.as_view(), name='page_ViewConfirmQL'),
	url(r'^add_cart/(?P<id_sp>\w+)/(?P<id_user>\w+)/$', AddCart.as_view(), name='page_AddCart'),
	url(r'^add_cart/empty/(?P<id_sp>\w+)/(?P<id_user>\w+)/$', AddCartEmpty.as_view(), name='page_AddCartEmpty'),
	url(r'^show_cart/$', BaseViewCart.as_view(), name='page_BaseViewCart'),		
	url(r'^add_product/(?P<id_cart>\w+)/(?P<id_product>\w+)/$', AddProduct.as_view(), name='page_AddProduct'),
	url(r'^minius_product/(?P<id_cart>\w+)/(?P<id_product>\w+)/$', MinusProduct.as_view(), name='page_MinusProduct'),
	url(r'^delete_product/(?P<id_cart>\w+)/isproduct/(?P<id_product>\w+)/$', DeleteCart, name='page_DeleteCart'),
	url(r'^is_buy/(?P<id_cart>\w+)/$', Buy, name='page_Buy'),
	url(r'^is_confirm/(?P<id_cart>\w+)/$', confirm, name='page_confirm'),
	url(r'^view_sanpham/(?P<user_to>\w+)/$', ViewSPUserBuy.as_view(), name='page_ViewSPUserBuy'),
]