# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-04 03:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0004_remove_cartitem_is_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
    ]
