# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-14 04:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0007_auto_20201206_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='sex',
        ),
    ]
