# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-16 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0008_auto_20201214_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
