# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-02 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('CreateAt', models.DateTimeField(auto_now=True)),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(blank=True, default=0, null=True)),
                ('sum_product', models.FloatField(blank=True, default=0, null=True)),
                ('id_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AD', 'Admin'), ('MN', 'Manager'), ('US', 'User')], default='US', max_length=10)),
                ('name', models.TextField(default='', max_length=100)),
                ('sex', models.CharField(choices=[('1', 'Nam'), ('2', 'Nữ'), ('3', 'Khác')], default='1', max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=300, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'pending'), ('confirm', 'confirm'), ('paid', 'paid'), ('shipping', 'shipping'), ('completed', 'completed')], max_length=10, null=True)),
                ('id_cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.Cart')),
                ('id_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=3000, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='pro_image')),
                ('price', models.FloatField(blank=True, default=0, null=True)),
                ('is_sale', models.BooleanField(default=False)),
                ('price_sale', models.FloatField(blank=True, default=0, null=True)),
                ('type', models.CharField(blank=True, max_length=300, null=True)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('for_male', models.BooleanField(default=False)),
                ('for_female', models.BooleanField(default=False)),
                ('TTs', models.TimeField(auto_now=True)),
                ('TTe', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='id_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Page.Product'),
        ),
    ]
