# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0005_cart_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
