# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-06 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Page', '0006_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
