# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-08-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Banhang', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumer',
            name='name',
            field=models.TextField(default='', max_length=100),
        ),
    ]
